#include "gfx3ds.hpp"

#include <cstdio>

// generated by picasso+bin2s from shaders/world.v.pica
extern const u8 world_shbin[];
extern const u32 world_shbin_size;
extern const u8 ui_shbin[];
extern const u32 ui_shbin_size;
extern const u8 entity_shbin[];
extern const u32 entity_shbin_size;

namespace {
    C3D_RenderTarget* topTarget = nullptr;
    C3D_RenderTarget* bottomTarget = nullptr;
    DVLB_s* worldDvlb = nullptr;
    DVLB_s* uiDvlb = nullptr;
    DVLB_s* entityDvlb = nullptr;
    shaderProgram_s worldProgram;
    shaderProgram_s uiProgram;
    shaderProgram_s entityProgram;
    int uLocMvp = -1;
    int uLocSky = -1;
    int uLocUiProj = -1;
    int uLocEntityMvp = -1;
    int uLocEntitySky = -1;

    C3D_Mtx projTilt;
    C3D_Mtx viewC3D;
    bool inFrame = false;
    C3D_FogLut fogLut;
    bool fogReady = false;

    C3D_RenderTarget* topRightTarget = nullptr;
    bool stereo = false;
    int currentEye = 0;
    u32 clearColor = 0;

    void glmToC3D(const glm::mat4& m, C3D_Mtx* out) {
        for (int row = 0; row < 4; row++) {
            out->r[row].x = m[0][row];
            out->r[row].y = m[1][row];
            out->r[row].z = m[2][row];
            out->r[row].w = m[3][row];
        }
    }
}

namespace gfx3ds {

bool init() {
    C3D_Init(C3D_DEFAULT_CMDBUF_SIZE * 2);

    topTarget = C3D_RenderTargetCreate(
        240, 400, GPU_RB_RGBA8, GPU_RB_DEPTH24_STENCIL8);
    if (!topTarget) {
        return false;
    }
    C3D_RenderTargetSetOutput(
        topTarget, GFX_TOP, GFX_LEFT,
        GX_TRANSFER_FLIP_VERT(0) | GX_TRANSFER_OUT_TILED(0) |
        GX_TRANSFER_RAW_COPY(0) |
        GX_TRANSFER_IN_FORMAT(GX_TRANSFER_FMT_RGBA8) |
        GX_TRANSFER_OUT_FORMAT(GX_TRANSFER_FMT_RGB8) |
        GX_TRANSFER_SCALING(GX_TRANSFER_SCALE_NO));

    worldDvlb = DVLB_ParseFile((u32*)world_shbin, world_shbin_size);
    if (!worldDvlb) {
        return false;
    }
    shaderProgramInit(&worldProgram);
    shaderProgramSetVsh(&worldProgram, &worldDvlb->DVLE[0]);
    uLocMvp = shaderInstanceGetUniformLocation(
        worldProgram.vertexShader, "mvp");
    uLocSky = shaderInstanceGetUniformLocation(
        worldProgram.vertexShader, "skylight");

    bottomTarget = C3D_RenderTargetCreate(
        240, 320, GPU_RB_RGBA8, GPU_RB_DEPTH16);
    if (!bottomTarget) {
        return false;
    }
    C3D_RenderTargetSetOutput(
        bottomTarget, GFX_BOTTOM, GFX_LEFT,
        GX_TRANSFER_FLIP_VERT(0) | GX_TRANSFER_OUT_TILED(0) |
        GX_TRANSFER_RAW_COPY(0) |
        GX_TRANSFER_IN_FORMAT(GX_TRANSFER_FMT_RGBA8) |
        GX_TRANSFER_OUT_FORMAT(GX_TRANSFER_FMT_RGB8) |
        GX_TRANSFER_SCALING(GX_TRANSFER_SCALE_NO));

    uiDvlb = DVLB_ParseFile((u32*)ui_shbin, ui_shbin_size);
    if (!uiDvlb) {
        return false;
    }
    shaderProgramInit(&uiProgram);
    shaderProgramSetVsh(&uiProgram, &uiDvlb->DVLE[0]);
    uLocUiProj = shaderInstanceGetUniformLocation(
        uiProgram.vertexShader, "proj");

    entityDvlb = DVLB_ParseFile((u32*)entity_shbin, entity_shbin_size);
    if (!entityDvlb) {
        return false;
    }
    shaderProgramInit(&entityProgram);
    shaderProgramSetVsh(&entityProgram, &entityDvlb->DVLE[0]);
    uLocEntityMvp = shaderInstanceGetUniformLocation(
        entityProgram.vertexShader, "mvp");
    uLocEntitySky = shaderInstanceGetUniformLocation(
        entityProgram.vertexShader, "skylight");

    return true;
}

void shutdown() {
    if (worldDvlb) {
        shaderProgramFree(&worldProgram);
        DVLB_Free(worldDvlb);
        worldDvlb = nullptr;
    }
    setStereo(false);
    if (topTarget) {
        C3D_RenderTargetDelete(topTarget);
        topTarget = nullptr;
    }
    C3D_Fini();
}

void beginFrame(float r, float g, float b) {
    C3D_FrameBegin(C3D_FRAME_SYNCDRAW);
    clearColor = (u32(r * 255) << 24) | (u32(g * 255) << 16) |
                 (u32(b * 255) << 8) | 0xff;
    C3D_RenderTargetClear(topTarget, C3D_CLEAR_ALL, clearColor, 0);
    if (topRightTarget) {
        // the right eye must be filled every frame or it shows stale garbage
        C3D_RenderTargetClear(topRightTarget, C3D_CLEAR_ALL, clearColor, 0);
    }
    C3D_FrameDrawOn(topTarget);
    currentEye = 0;
    inFrame = true;
}

extern "C" void vc3ds_mesh_collect();

void endFrame() {
    C3D_FrameEnd(0);
    inFrame = false;
    vc3ds_mesh_collect();
}

void useWorldPipeline() {
    C3D_BindProgram(&worldProgram);

    // ChunkVertex: pos float3, uv float2, color u8x4 norm, normal u8x4 norm
    C3D_AttrInfo* attrInfo = C3D_GetAttrInfo();
    AttrInfo_Init(attrInfo);
    AttrInfo_AddLoader(attrInfo, 0, GPU_FLOAT, 3);
    AttrInfo_AddLoader(attrInfo, 1, GPU_FLOAT, 2);
    AttrInfo_AddLoader(attrInfo, 2, GPU_UNSIGNED_BYTE, 4);
    AttrInfo_AddLoader(attrInfo, 3, GPU_UNSIGNED_BYTE, 4);

    // texture0 * vertex color
    C3D_TexEnv* env = C3D_GetTexEnv(0);
    C3D_TexEnvInit(env);
    C3D_TexEnvSrc(env, C3D_Both, GPU_TEXTURE0, GPU_PRIMARY_COLOR, GPU_PRIMARY_COLOR);
    C3D_TexEnvFunc(env, C3D_Both, GPU_MODULATE);

    C3D_FVUnifSet(GPU_VERTEX_SHADER, uLocSky, 1.0f, 1.0f, 1.0f, 1.0f);
    if (!fogReady) {
        // denser fog: hides the edge of the lit/generated zone
        FogLut_Exp(&fogLut, 0.024f, 1.3f, 0.1f, 120.0f);
        fogReady = true;
    }
    C3D_FogGasMode(GPU_FOG, GPU_PLAIN_DENSITY, false);
    // fog color = sky clear color (0.55, 0.75, 0.95)
    C3D_FogColor(0x00F2BF8C);
    C3D_FogLutBind(&fogLut);
    C3D_DepthTest(true, GPU_GREATER, GPU_WRITE_ALL);
    C3D_CullFace(GPU_CULL_NONE);
    C3D_AlphaTest(true, GPU_GREATER, 20);
    C3D_SetScissor(GPU_SCISSOR_DISABLE, 0, 0, 0, 0);
    C3D_AlphaBlend(
        GPU_BLEND_ADD, GPU_BLEND_ADD,
        GPU_SRC_ALPHA, GPU_ONE_MINUS_SRC_ALPHA,
        GPU_SRC_ALPHA, GPU_ONE_MINUS_SRC_ALPHA);
}

void setViewProjection(
    const glm::mat4& view, float fovDeg, float zNear, float zFar, float focalLen) {
    if (stereo && focalLen > 0.0f) {
        // slider at 0 gives iod 0, i.e. both eyes identical
        float iod = osGet3DSliderState() * focalLen * 0.035f;
        Mtx_PerspStereoTilt(
            &projTilt, C3D_AngleFromDegrees(fovDeg), C3D_AspectRatioTop,
            zNear, zFar, currentEye == 0 ? -iod : iod, focalLen, false);
    } else {
        Mtx_PerspTilt(
            &projTilt, C3D_AngleFromDegrees(fovDeg), C3D_AspectRatioTop,
            zNear, zFar, false);
    }
    glmToC3D(view, &viewC3D);
}

void setStereo(bool enabled) {
    if (enabled == stereo) {
        return;
    }
    stereo = enabled;
    if (enabled) {
        topRightTarget = C3D_RenderTargetCreate(
            240, 400, GPU_RB_RGBA8, GPU_RB_DEPTH24_STENCIL8);
        if (!topRightTarget) {
            stereo = false;   // no VRAM for it: stay flat rather than fail
            return;
        }
        C3D_RenderTargetSetOutput(
            topRightTarget, GFX_TOP, GFX_RIGHT,
            GX_TRANSFER_FLIP_VERT(0) | GX_TRANSFER_OUT_TILED(0) |
            GX_TRANSFER_RAW_COPY(0) |
            GX_TRANSFER_IN_FORMAT(GX_TRANSFER_FMT_RGBA8) |
            GX_TRANSFER_OUT_FORMAT(GX_TRANSFER_FMT_RGB8) |
            GX_TRANSFER_SCALING(GX_TRANSFER_SCALE_NO));
    } else if (topRightTarget) {
        C3D_RenderTargetDelete(topRightTarget);
        topRightTarget = nullptr;
    }
    gfxSet3D(stereo);
}

int eyes() {
    return (stereo && topRightTarget) ? 2 : 1;
}

void setEye(int eye) {
    currentEye = (eye != 0 && topRightTarget) ? 1 : 0;
    C3D_FrameDrawOn(currentEye ? topRightTarget : topTarget);
    useWorldPipeline();
}

void setModel(const glm::mat4& model) {
    C3D_Mtx modelC3D, viewModel, mvp;
    glmToC3D(model, &modelC3D);
    Mtx_Multiply(&viewModel, &viewC3D, &modelC3D);
    Mtx_Multiply(&mvp, &projTilt, &viewModel);
    C3D_FVUnifMtx4x4(GPU_VERTEX_SHADER, uLocMvp, &mvp);
}

void beginTopUI() {
    C3D_FrameDrawOn(topTarget);

    C3D_BindProgram(&uiProgram);
    C3D_AttrInfo* attrInfo = C3D_GetAttrInfo();
    AttrInfo_Init(attrInfo);
    AttrInfo_AddLoader(attrInfo, 0, GPU_FLOAT, 2);
    AttrInfo_AddLoader(attrInfo, 1, GPU_FLOAT, 2);
    AttrInfo_AddLoader(attrInfo, 2, GPU_FLOAT, 4);

    C3D_TexEnv* env = C3D_GetTexEnv(0);
    C3D_TexEnvInit(env);
    C3D_TexEnvSrc(env, C3D_Both, GPU_TEXTURE0, GPU_PRIMARY_COLOR, GPU_PRIMARY_COLOR);
    C3D_TexEnvFunc(env, C3D_Both, GPU_MODULATE);

    C3D_DepthTest(false, GPU_GREATER, GPU_WRITE_COLOR);
    C3D_CullFace(GPU_CULL_NONE);
    C3D_AlphaTest(false, GPU_GREATER, 0);
    C3D_FogGasMode(GPU_NO_FOG, GPU_PLAIN_DENSITY, false);
    C3D_SetScissor(GPU_SCISSOR_DISABLE, 0, 0, 0, 0);
    C3D_AlphaBlend(
        GPU_BLEND_ADD, GPU_BLEND_ADD,
        GPU_SRC_ALPHA, GPU_ONE_MINUS_SRC_ALPHA,
        GPU_SRC_ALPHA, GPU_ONE_MINUS_SRC_ALPHA);

    C3D_Mtx proj;
    Mtx_OrthoTilt(&proj, 0.0f, 400.0f, 240.0f, 0.0f, -1.0f, 1.0f, false);
    C3D_FVUnifMtx4x4(GPU_VERTEX_SHADER, uLocUiProj, &proj);
}

void useEntityPipeline() {
    C3D_BindProgram(&entityProgram);

    // MainBatchVertex: pos f3, uv f2, tint f3, light u8x4, normal u8x4
    C3D_AttrInfo* attrInfo = C3D_GetAttrInfo();
    AttrInfo_Init(attrInfo);
    AttrInfo_AddLoader(attrInfo, 0, GPU_FLOAT, 3);
    AttrInfo_AddLoader(attrInfo, 1, GPU_FLOAT, 2);
    AttrInfo_AddLoader(attrInfo, 2, GPU_FLOAT, 3);
    AttrInfo_AddLoader(attrInfo, 3, GPU_UNSIGNED_BYTE, 4);
    AttrInfo_AddLoader(attrInfo, 4, GPU_UNSIGNED_BYTE, 4);

    C3D_TexEnv* env = C3D_GetTexEnv(0);
    C3D_TexEnvInit(env);
    C3D_TexEnvSrc(env, C3D_Both, GPU_TEXTURE0, GPU_PRIMARY_COLOR, GPU_PRIMARY_COLOR);
    C3D_TexEnvFunc(env, C3D_Both, GPU_MODULATE);

    C3D_DepthTest(true, GPU_GREATER, GPU_WRITE_ALL);
    C3D_CullFace(GPU_CULL_NONE);
    C3D_AlphaTest(true, GPU_GREATER, 20);
    C3D_SetScissor(GPU_SCISSOR_DISABLE, 0, 0, 0, 0);
    C3D_AlphaBlend(
        GPU_BLEND_ADD, GPU_BLEND_ADD,
        GPU_SRC_ALPHA, GPU_ONE_MINUS_SRC_ALPHA,
        GPU_SRC_ALPHA, GPU_ONE_MINUS_SRC_ALPHA);
    C3D_FogGasMode(GPU_FOG, GPU_PLAIN_DENSITY, false);
    C3D_FogColor(0x00F2BF8C);
    C3D_FogLutBind(&fogLut);

    // vertices come in world space: mvp = proj * view
    C3D_Mtx mvp;
    Mtx_Multiply(&mvp, &projTilt, &viewC3D);
    C3D_FVUnifMtx4x4(GPU_VERTEX_SHADER, uLocEntityMvp, &mvp);
    C3D_FVUnifSet(GPU_VERTEX_SHADER, uLocEntitySky, 1.0f, 1.0f, 1.0f, 1.0f);
}

void beginBottomUI(float r, float g, float b) {
    u32 clr = (u32(r * 255) << 24) | (u32(g * 255) << 16) |
              (u32(b * 255) << 8) | 0xff;
    C3D_RenderTargetClear(bottomTarget, C3D_CLEAR_ALL, clr, 0);
    C3D_FrameDrawOn(bottomTarget);

    C3D_BindProgram(&uiProgram);
    C3D_AttrInfo* attrInfo = C3D_GetAttrInfo();
    AttrInfo_Init(attrInfo);
    AttrInfo_AddLoader(attrInfo, 0, GPU_FLOAT, 2);
    AttrInfo_AddLoader(attrInfo, 1, GPU_FLOAT, 2);
    AttrInfo_AddLoader(attrInfo, 2, GPU_FLOAT, 4);

    C3D_TexEnv* env = C3D_GetTexEnv(0);
    C3D_TexEnvInit(env);
    C3D_TexEnvSrc(env, C3D_Both, GPU_TEXTURE0, GPU_PRIMARY_COLOR, GPU_PRIMARY_COLOR);
    C3D_TexEnvFunc(env, C3D_Both, GPU_MODULATE);

    C3D_DepthTest(false, GPU_GREATER, GPU_WRITE_COLOR);
    C3D_CullFace(GPU_CULL_NONE);
    C3D_AlphaTest(false, GPU_GREATER, 0);
    C3D_FogGasMode(GPU_NO_FOG, GPU_PLAIN_DENSITY, false);
    C3D_AlphaBlend(
        GPU_BLEND_ADD, GPU_BLEND_ADD,
        GPU_SRC_ALPHA, GPU_ONE_MINUS_SRC_ALPHA,
        GPU_SRC_ALPHA, GPU_ONE_MINUS_SRC_ALPHA);

    C3D_Mtx proj;
    Mtx_OrthoTilt(&proj, 0.0f, 320.0f, 240.0f, 0.0f, -1.0f, 1.0f, false);
    C3D_FVUnifMtx4x4(GPU_VERTEX_SHADER, uLocUiProj, &proj);
}

}  // namespace gfx3ds
